// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwjsqvbnsbifcidtqpcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53anNxdmJuc2JpZmNpZHRxcGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1Njc2NDcsImV4cCI6MjA2NDE0MzY0N30.Fr5RXCW8hYHADsyd9BKKGCV9nogoIHN7W1pzXbs2MEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);